"""Create the initial database schema for the monitoring domain.

This migration creates the core tables required by the MVP: sensor types,
sensors, sensor readings, the monitored tank and operational alerts.
"""

# Generated by Django 5.2.14 on 2026-05-14 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Apply the first version of the monitoring app database schema."""

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estanque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('capacidad_litros', models.PositiveIntegerField(default=1000)),
                ('nivel_actual', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'estanque',
                'verbose_name_plural': 'estanques',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='LecturaSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_agua', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('bidones_producidos', models.PositiveIntegerField(default=0)),
                ('ph', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('datos_originales', models.JSONField(blank=True, default=dict)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'lectura de sensor',
                'verbose_name_plural': 'lecturas de sensores',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=120)),
                ('ubicacion', models.CharField(blank=True, max_length=150)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'sensor',
                'verbose_name_plural': 'sensores',
                'ordering': ['tipo__nombre', 'identificador'],
            },
        ),
        migrations.CreateModel(
            name='TipoSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('unidad_medida', models.CharField(blank=True, max_length=20)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'tipo de sensor',
                'verbose_name_plural': 'tipos de sensor',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('severidad', models.CharField(choices=[('INFO', 'Informativa'), ('ADVERTENCIA', 'Advertencia'), ('CRITICA', 'Critica')], default='ADVERTENCIA', max_length=20)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('RESUELTA', 'Resuelta')], default='ACTIVA', max_length=20)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('resuelta_en', models.DateTimeField(blank=True, null=True)),
                ('estanque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='monitoreo.estanque')),
                ('lectura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='monitoreo.lecturasensor')),
            ],
            options={
                'verbose_name': 'alerta',
                'verbose_name_plural': 'alertas',
                'ordering': ['-creada_en'],
            },
        ),
        migrations.AddField(
            model_name='lecturasensor',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lecturas', to='monitoreo.sensor'),
        ),
        migrations.AddField(
            model_name='estanque',
            name='sensor_nivel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estanques', to='monitoreo.sensor'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sensores', to='monitoreo.tiposensor'),
        ),
        migrations.AddConstraint(
            model_name='lecturasensor',
            constraint=models.CheckConstraint(condition=models.Q(('nivel_agua__isnull', True), models.Q(('nivel_agua__gte', 0), ('nivel_agua__lte', 100)), _connector='OR'), name='lectura_nivel_agua_entre_0_y_100'),
        ),
        migrations.AddConstraint(
            model_name='lecturasensor',
            constraint=models.CheckConstraint(condition=models.Q(('ph__isnull', True), models.Q(('ph__gte', 0), ('ph__lte', 14)), _connector='OR'), name='lectura_ph_entre_0_y_14'),
        ),
        migrations.AddConstraint(
            model_name='estanque',
            constraint=models.CheckConstraint(condition=models.Q(('nivel_actual__gte', 0), ('nivel_actual__lte', 100)), name='estanque_nivel_actual_entre_0_y_100'),
        ),
        migrations.AddConstraint(
            model_name='sensor',
            constraint=models.UniqueConstraint(fields=('tipo', 'identificador'), name='sensor_tipo_identificador_unico'),
        ),
    ]
